import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-hospital-observation-status-revenue-integrity",
  "engine": "recovery",
  "title": "Hospital Observation Status Revenue Integrity",
  "shortTitle": "Hospital Observation Status Revenue Integrity",
  "tagline": "Protect reimbursement by validating observation, inpatient, and outpatient status against documentation and payer rules.",
  "industry": "Hospital Revenue Integrity",
  "buyer": "Hospitals and utilization-management teams",
  "uiPort": 4644,
  "apiPort": 5644,
  "accent": "#7e22ce",
  "currency": "USD",
  "primaryOutcome": "Hospital Observation Status Revenue Integrity converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect orders, medical-necessity evidence, timestamps, bed status, condition codes, utilization reviews, claims, payer rules, denials, and remittances in one accountable workflow. Protect reimbursement by validating observation, inpatient, and outpatient status against documentation and payer rules.",
  "calculation": {
    "actualKey": "receivedAmount",
    "expectedKey": "entitledAmount",
    "actualLabel": "Received or Recognized Amount",
    "expectedLabel": "Contract or Rule-Supported Entitlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Hospital Observation Status Revenue Integrity evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("encounter-timeline-reconstruction","HOS01","Encounter timeline reconstruction","Execute encounter timeline reconstruction using orders, medical-necessity evidence, timestamps, bed status, condition codes, utilization reviews, claims, payer rules, denials, and remittances.","Produce a governed encounter timeline reconstruction decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Hospital / Patient Encounter","text","Hospital / Patient Encounter · Standard Case"],["caseReference","Encounter timeline reconstruction Reference","text","HOS01-2026-001"],["receivedAmount","Received or Recognized Amount","currency",521250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",630713],["domainDriver","Encounter Status","select","Observation",["Observation","Inpatient","Outpatient in bed"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Encounter timeline reconstruction case","Admission order validation case","Observation order validation case","Two-midnight evidence case","Condition code 44 control case"]}),
feature("admission-order-validation","HOS02","Admission order validation","Execute admission order validation using orders, medical-necessity evidence, timestamps, bed status, condition codes, utilization reviews, claims, payer rules, denials, and remittances.","Produce a governed admission order validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Hospital / Patient Encounter","text","Hospital / Patient Encounter · Standard Case"],["caseReference","Admission order validation Reference","text","HOS02-2026-001"],["receivedAmount","Received or Recognized Amount","currency",521250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",630713],["domainDriver","Encounter Status","select","Observation",["Observation","Inpatient","Outpatient in bed"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Encounter timeline reconstruction case","Admission order validation case","Observation order validation case","Two-midnight evidence case","Condition code 44 control case"]}),
feature("observation-order-validation","HOS03","Observation order validation","Execute observation order validation using orders, medical-necessity evidence, timestamps, bed status, condition codes, utilization reviews, claims, payer rules, denials, and remittances.","Produce a governed observation order validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Hospital / Patient Encounter","text","Hospital / Patient Encounter · Standard Case"],["caseReference","Observation order validation Reference","text","HOS03-2026-001"],["receivedAmount","Received or Recognized Amount","currency",521250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",630713],["domainDriver","Encounter Status","select","Observation",["Observation","Inpatient","Outpatient in bed"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Encounter timeline reconstruction case","Admission order validation case","Observation order validation case","Two-midnight evidence case","Condition code 44 control case"]}),
feature("two-midnight-evidence","HOS04","Two-midnight evidence","Execute two-midnight evidence using orders, medical-necessity evidence, timestamps, bed status, condition codes, utilization reviews, claims, payer rules, denials, and remittances.","Produce a governed two-midnight evidence decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Hospital / Patient Encounter","text","Hospital / Patient Encounter · Standard Case"],["caseReference","Two-midnight evidence Reference","text","HOS04-2026-001"],["receivedAmount","Received or Recognized Amount","currency",521250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",630713],["domainDriver","Encounter Status","select","Observation",["Observation","Inpatient","Outpatient in bed"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Encounter timeline reconstruction case","Admission order validation case","Observation order validation case","Two-midnight evidence case","Condition code 44 control case"]}),
feature("condition-code-44-control","HOS05","Condition code 44 control","Execute condition code 44 control using orders, medical-necessity evidence, timestamps, bed status, condition codes, utilization reviews, claims, payer rules, denials, and remittances.","Produce a governed condition code 44 control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Hospital / Patient Encounter","text","Hospital / Patient Encounter · Standard Case"],["caseReference","Condition code 44 control Reference","text","HOS05-2026-001"],["receivedAmount","Received or Recognized Amount","currency",521250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",630713],["domainDriver","Encounter Status","select","Observation",["Observation","Inpatient","Outpatient in bed"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Encounter timeline reconstruction case","Admission order validation case","Observation order validation case","Two-midnight evidence case","Condition code 44 control case"]}),
feature("utilization-review-queue","HOS06","Utilization review queue","Execute utilization review queue using orders, medical-necessity evidence, timestamps, bed status, condition codes, utilization reviews, claims, payer rules, denials, and remittances.","Produce a governed utilization review queue decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Hospital / Patient Encounter","text","Hospital / Patient Encounter · Standard Case"],["caseReference","Utilization review queue Reference","text","HOS06-2026-001"],["receivedAmount","Received or Recognized Amount","currency",521250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",630713],["domainDriver","Encounter Status","select","Observation",["Observation","Inpatient","Outpatient in bed"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Encounter timeline reconstruction case","Admission order validation case","Observation order validation case","Two-midnight evidence case","Condition code 44 control case"]}),
feature("medical-necessity-scoring","HOS07","Medical necessity scoring","Execute medical necessity scoring using orders, medical-necessity evidence, timestamps, bed status, condition codes, utilization reviews, claims, payer rules, denials, and remittances.","Produce a governed medical necessity scoring decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Hospital / Patient Encounter","text","Hospital / Patient Encounter · Standard Case"],["caseReference","Medical necessity scoring Reference","text","HOS07-2026-001"],["receivedAmount","Received or Recognized Amount","currency",521250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",630713],["domainDriver","Encounter Status","select","Observation",["Observation","Inpatient","Outpatient in bed"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Encounter timeline reconstruction case","Admission order validation case","Observation order validation case","Two-midnight evidence case","Condition code 44 control case"]}),
feature("bed-status-reconciliation","HOS08","Bed-status reconciliation","Execute bed-status reconciliation using orders, medical-necessity evidence, timestamps, bed status, condition codes, utilization reviews, claims, payer rules, denials, and remittances.","Produce a governed bed-status reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Hospital / Patient Encounter","text","Hospital / Patient Encounter · Standard Case"],["caseReference","Bed-status reconciliation Reference","text","HOS08-2026-001"],["receivedAmount","Received or Recognized Amount","currency",521250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",630713],["domainDriver","Encounter Status","select","Observation",["Observation","Inpatient","Outpatient in bed"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Encounter timeline reconstruction case","Admission order validation case","Observation order validation case","Two-midnight evidence case","Condition code 44 control case"]}),
feature("hours-and-unit-calculation","HOS09","Hours and unit calculation","Execute hours and unit calculation using orders, medical-necessity evidence, timestamps, bed status, condition codes, utilization reviews, claims, payer rules, denials, and remittances.","Produce a governed hours and unit calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Hospital / Patient Encounter","text","Hospital / Patient Encounter · Standard Case"],["caseReference","Hours and unit calculation Reference","text","HOS09-2026-001"],["receivedAmount","Received or Recognized Amount","currency",521250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",630713],["domainDriver","Encounter Status","select","Observation",["Observation","Inpatient","Outpatient in bed"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Encounter timeline reconstruction case","Admission order validation case","Observation order validation case","Two-midnight evidence case","Condition code 44 control case"]}),
feature("ancillary-charge-capture","HOS10","Ancillary charge capture","Execute ancillary charge capture using orders, medical-necessity evidence, timestamps, bed status, condition codes, utilization reviews, claims, payer rules, denials, and remittances.","Produce a governed ancillary charge capture decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Hospital / Patient Encounter","text","Hospital / Patient Encounter · Standard Case"],["caseReference","Ancillary charge capture Reference","text","HOS10-2026-001"],["receivedAmount","Received or Recognized Amount","currency",521250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",630713],["domainDriver","Encounter Status","select","Observation",["Observation","Inpatient","Outpatient in bed"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Encounter timeline reconstruction case","Admission order validation case","Observation order validation case","Two-midnight evidence case","Condition code 44 control case"]}),
feature("claim-status-coding","HOS11","Claim status coding","Execute claim status coding using orders, medical-necessity evidence, timestamps, bed status, condition codes, utilization reviews, claims, payer rules, denials, and remittances.","Produce a governed claim status coding decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Hospital / Patient Encounter","text","Hospital / Patient Encounter · Standard Case"],["caseReference","Claim status coding Reference","text","HOS11-2026-001"],["receivedAmount","Received or Recognized Amount","currency",521250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",630713],["domainDriver","Encounter Status","select","Observation",["Observation","Inpatient","Outpatient in bed"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Encounter timeline reconstruction case","Admission order validation case","Observation order validation case","Two-midnight evidence case","Condition code 44 control case"]}),
feature("denial-root-cause-analysis","HOS12","Denial root-cause analysis","Execute denial root-cause analysis using orders, medical-necessity evidence, timestamps, bed status, condition codes, utilization reviews, claims, payer rules, denials, and remittances.","Produce a governed denial root-cause analysis decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Hospital / Patient Encounter","text","Hospital / Patient Encounter · Standard Case"],["caseReference","Denial root-cause analysis Reference","text","HOS12-2026-001"],["receivedAmount","Received or Recognized Amount","currency",521250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",630713],["domainDriver","Encounter Status","select","Observation",["Observation","Inpatient","Outpatient in bed"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Encounter timeline reconstruction case","Admission order validation case","Observation order validation case","Two-midnight evidence case","Condition code 44 control case"]}),
feature("appeal-packet-generation","HOS13","Appeal packet generation","Execute appeal packet generation using orders, medical-necessity evidence, timestamps, bed status, condition codes, utilization reviews, claims, payer rules, denials, and remittances.","Produce a governed appeal packet generation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Hospital / Patient Encounter","text","Hospital / Patient Encounter · Standard Case"],["caseReference","Appeal packet generation Reference","text","HOS13-2026-001"],["receivedAmount","Received or Recognized Amount","currency",521250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",630713],["domainDriver","Encounter Status","select","Observation",["Observation","Inpatient","Outpatient in bed"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Encounter timeline reconstruction case","Admission order validation case","Observation order validation case","Two-midnight evidence case","Condition code 44 control case"]}),
feature("payment-reconciliation","HOS14","Payment reconciliation","Execute payment reconciliation using orders, medical-necessity evidence, timestamps, bed status, condition codes, utilization reviews, claims, payer rules, denials, and remittances.","Produce a governed payment reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Hospital / Patient Encounter","text","Hospital / Patient Encounter · Standard Case"],["caseReference","Payment reconciliation Reference","text","HOS14-2026-001"],["receivedAmount","Received or Recognized Amount","currency",521250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",630713],["domainDriver","Encounter Status","select","Observation",["Observation","Inpatient","Outpatient in bed"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Encounter timeline reconstruction case","Admission order validation case","Observation order validation case","Two-midnight evidence case","Condition code 44 control case"]}),
feature("status-revenue-analytics","HOS15","Status revenue analytics","Execute status revenue analytics using orders, medical-necessity evidence, timestamps, bed status, condition codes, utilization reviews, claims, payer rules, denials, and remittances.","Produce a governed status revenue analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Hospital / Patient Encounter","text","Hospital / Patient Encounter · Standard Case"],["caseReference","Status revenue analytics Reference","text","HOS15-2026-001"],["receivedAmount","Received or Recognized Amount","currency",521250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",630713],["domainDriver","Encounter Status","select","Observation",["Observation","Inpatient","Outpatient in bed"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Encounter timeline reconstruction case","Admission order validation case","Observation order validation case","Two-midnight evidence case","Condition code 44 control case"]})
]);
